import { AlertStatus } from 'enums/alerts';
import { Alert } from 'interfaces/Alert';

export const mockAlerts: Alert[] = [
  {
    id: '1',
    name: 'No Ad Spend',
    source: 'Source name',
    parameter: 'If',
    operation: 'Is greater than',
    clients: 12,
    date: '2023-04-21',
    fires: 0,
    status: AlertStatus.NEW,
    value: -30,
  },
  {
    id: '2',
    name: 'No Ad Spend',
    source: 'Source name',
    parameter: 'If',
    operation: 'Is greater than',
    clients: 12,
    date: new Date(),
    fires: 0,
    status: AlertStatus.ARCHIVE,
    value: 0,
  },
  {
    id: '3',
    name: 'No Ad Spend',
    source: 'Source name',
    parameter: 'If',
    operation: 'Is greater than',
    clients: 12,
    date: '2021-07-21',
    fires: 0,
    status: AlertStatus.NEW,
    value: 20,
  },
  {
    id: '4',
    name: 'No Ad Spend',
    source: 'Source name',
    parameter: 'If',
    operation: 'Is greater than',
    clients: 12,
    date: '2023/07/22',
    fires: 0,
    status: AlertStatus.ARCHIVE,
    value: 0,
  },
];
